# Generated by Django 5.1.1 on 2025-08-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-last_update']},
        ),
    ]
